### ISSUE TITLE
Create overall summary report

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine-integration-testing#1]
A report should be created that summarizes all the tests. Useful to check if TE and the tests can be released.

TE integration testing - date time

TE version - build
- Default build OK
  - TE URL opens correctly
  -  There are test publicly available 
- User can be created and logins 
- User can run a test (forms appears) 
- User get test result

And for each test

TestName Version - build
- Test can be run (forms appears)
- Test run finishes successfully  (result can fail - but it should finish to expected completion)

**Comment by upendra-sachan** [comment]
Fixed in https://github.com/opengeospatial/teamengine-integration-testing/commit/c4bbfd04a7adfa185db7417fa5317368ebd974da
