### ISSUE TITLE
Provide better message if run-test.sh doesn't find apache-jmeter-2.13/bin/jmeter

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine-integration-testing#12]
re: run-test.sh https://github.com/opengeospatial/teamengine-integration-testing/commit/923a4b2f5abfe65bc280baca4e1f83bf5baaba35
When running in mac and without any paramerters the script echoes the following:

```
  sh: /Users/lbermudez/apache-jmeter-2.13/bin/jmeter: No such file or directory
```

The script should first check to see if the jmeter library is properly installed and if not it should provide an error message that tells what the user needs to do. For example:
 The script needs to find bin/jmeter script under then apache-jmeter-2.13 folder.  apache-jmeter-2.13 needs to be installed in the system or under the users default directory.

**Comment by keshavnangare** [comment]
Fixed with this commit e655b21e7ba38ff8dd9eaac1e90286803af968b2
