### ISSUE TITLE
Create full integration testing for GML

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine-integration-testing#7]
In the TE integration testing I would strongly recommend invoking the GML test suite four times:
1.       Using the REST API via GET
2.       Using the REST API via POST
3.       Web interface providing file URI (gml-uri)
4.       Web interface uploading the GML document
5.       Test via command line 

For integration tests 1 and 3 the test run argument value could be a file URI (e.g. file:///tmp/ProtectedSites-1.xml).

NOTE: In all cases the results should normally report one failing test (under “GML Documents”):

Valid surface orientation: “Exterior boundary of surface with @gml:id='EN.NMA.PS.7174d7fb-7b0f-4153-821b-1c758032c83d-0' is not oriented CCW with respect to the up-normal.”

**Comment by bermud** [comment]
I don't see the GML32-POST and GET. Can we bundle all these inside GML32 folder? Each folder should use the abbreviation without the 'ETS-'

**Comment by keshavnangare** [comment]
We have included the GML32-POST and GET into the REST_API directory.

Created script for the following:
          1.GML32 REST API:
               &nbsp; &nbsp; &nbsp; &nbsp;  -For GET and POST method.
          2.Web interface providing file URI (gml-uri).
          3.Web interface uploading the GML document.
          4. Test via command line. (Not Completed)

All the jmeter script access the runtime parameter from the "test.properties" instead on csv file.
