### ISSUE TITLE
Config files

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine-integration-testing#9]
I see that for every standards we have a csv file. I will prefer to have a main config csv file at the root folder, call it `config.csv`, where you can specify the test and reference implementation. For example each line will have:

wms13, 1.15-SNAPSHOT, http://cite.demo.opengeo.org:8080/geoserver_wms13/wms?service=wms&request=getcapabilities&version=1.3.0.

Also, you should be able to specify more than one reference implementation, by just repeating the line

**Comment by keshavnangare** [comment]
Fixed with this commit c5ad6673d3b8dafe447f9fce7c927caf363d04bd
